[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node minimal-server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Port configuration
[deploy.variables]
PORT = "8080"

# Resource allocation
[resources.production]
cpu = 0.25
memory = 512 