[build]
builder = "NIXPACKS"
buildCommand = "npm install --production --no-fund --no-audit"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Port configuration
[deploy.variables]
PORT = "8080"
NODE_ENV = "production"
NPM_CONFIG_LOGLEVEL = "error"

# Resource allocation
[resources.production]
cpu = 0.1
memory = 256 