[build]
builder = "NIXPACKS"
buildCommand = "npm ci --omit=dev"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

# Port configuration
[deploy.variables]
PORT = "8080"

# Resource allocation
[resources.production]
cpu = 0.25
memory = 512 