[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node basic-server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Port configuration
[deploy.variables]
PORT = "8080"
NODE_ENV = "production"

# Resource allocation
[resources.production]
cpu = 0.1
memory = 256 