[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Resource allocation
[resources.production]
cpu = 0.25
memory = 512 