services:
  - type: web
    name: pay-backend-iu9e
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false # This means it's a secret and should be manually set in Render dashboard
      - key: REACT_APP_API_URL
        sync: false # Set this in the Render dashboard to your deployed app URL
      - key: BACKEND_URL
        value: https://pay-backend-iu9e.onrender.com # Set explicitly for consistency
      - key: RENDER_URL
        fromService:
          name: pay-backend-iu9e
          type: web
          property: url # This will automatically set to the URL of the web service
  
  # Keep the app alive with a background worker
  - type: worker
    name: pay-keep-alive
    env: node
    plan: free # Free tier is enough for a simple ping service
    buildCommand: npm install
    startCommand: npm run keep-alive
    envVars:
      - key: RENDER_URL
        value: https://pay-backend-iu9e.onrender.com # Set explicitly to match backend URL 